### ISSUE TITLE
Testhost process exited with error: Unhandled exception. System.Net.Sockets.SocketException (10022): An invalid argument was supplied.

### ISSUE THREAD

**Issue by RisuSofos** [xunit/visualstudio.xunit#307]
When I run my tests with `dotnet test` I get the following error and see (0 passed, 0 failed, 0 skipped)
```
  Determining projects to restore...
  Restored Z:\Source\AutoBackup\AutoBackup.Test\AutoBackup.Test.csproj (in 393 ms).
  2 of 3 projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  AutoBackup.Test -> Z:\Source\AutoBackup\AutoBackup.Test\bin\Debug\net6.0\AutoBackup.Test.dll
Test run for Z:\Source\AutoBackup\AutoBackup.Test\bin\Debug\net6.0\AutoBackup.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.2.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: Unhandled exception. System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket..ctor(SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.TcpClient.InitializeClientSocket()
   at System.Net.Sockets.TcpClient..ctor(AddressFamily family)
   at System.Net.Sockets.TcpClient..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient..ctor(Func`2 channelFactory)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.CommunicationEndpointFactory.Create(ConnectionRole role)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.InitializeCommunication()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
. Please check the diagnostic logs for more information.

Test Run Aborted.
```
I have tried reinstalling visualstudio, using an older version of both xunit and visualstudio, and was only able to get it to work after trying it on another computer.

**Comment by bradwilson** [comment]
I see `Z:` as your source drive. Is this a network drive? If so, I'm guessing this isn't supported by VSTest because of permission issues. Either way, this has nothing to do with us (none of our code is visible in the call stack) so I recommend, if you can still reproduce this, to open an issue against VSTest.
