### ISSUE TITLE
Update README with build & test instructions

### ISSUE THREAD

**Issue by bradwilson** [xunit/visualstudio.xunit#361]
The README is currently missing:

- Minimum requirements for Visual Studio
- Instructions on how to build & run the tests (ideally, a command line tool to do so)

**Comment by codingdave** [comment]
I am glad this case exists, as I fail to run the tests. It would be greate to have some instructions on what to do to be able to debug tests inside the xunit project using VisualStudio.

Steps that work for me (for v2 and main):
checkout xunit with its submodules
./build.ps1

Now I want to debug a unit test of xunit in Visual Studio 17.4.4. Nuget Restore and (re)builiding works without issues. No tests show up in the test explorer. The test output mentions:

    Log level is set to Informational (Default).
    Connected to test environment '< Local Windows Environment >'
    Test data store opened in 0.264 sec.
    Test project test.xunit.runner.msbuild does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    ========== Starting test discovery ==========
    Test project test.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    ========== Test discovery aborted: 0 Tests found in 349.5 ms ==========
    Test project test.xunit.console does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    ========== Starting test discovery ==========
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    ========== Test discovery aborted: 0 Tests found in 12.1 ms ==========
    Test project test.xunit.runner.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.tdnet does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.execution does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.assert does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.reporters does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.assert does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.console does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit1 does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.console does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.execution does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.console does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.assert does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.execution does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.reporters does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.execution does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.msbuild does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.assert does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.reporters does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.reporters does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.tdnet does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit1 does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    ========== Starting test discovery ==========
    Test project test.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.assert does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.assert does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.console does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    No test is available in E:\Projects\xunit\src\xunit.runner.utility\bin\Debug\net452\xunit.runner.utility.net452.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    Test project test.xunit.console does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    No test is available in E:\Projects\xunit\test\test.xunit.assert\bin\Debug\net452\test.xunit.assert.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\test\test.xunit.runner.msbuild\bin\Debug\net452\test.xunit.runner.msbuild.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\test\test.xunit.console\bin\Debug\net452\test.xunit.console.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\test\test.xunit.execution\bin\Debug\net452\test.xunit.execution.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.execution\bin\Debug\net452\xunit.execution.desktop.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\test\test.utility\bin\Debug\net452\test.utility.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.runner.assemblies\bin\Debug\net452\xunit.runner.assemblies.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.runner.tdnet\bin\Debug\net452\xunit.runner.tdnet.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.console\bin\Debug\net452\xunit.console.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.runner.reporters\bin\Debug\net452\xunit.runner.reporters.net452.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.runner.msbuild\bin\Debug\net452\xunit.runner.msbuild.net452.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
       at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
    Test project test.xunit.execution does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.execution does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.msbuild does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    No test is available in E:\Projects\xunit\test\test.xunit.runner.reporters\bin\Debug\net452\test.xunit.runner.reporters.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\test\test.xunit.runner.tdnet\bin\Debug\net452\test.xunit.runner.tdnet.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\test\test.xunit.runner.utility\bin\Debug\net452\test.xunit.runner.utility.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.console\bin\Debug\net461\xunit.console.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.console\bin\Debug\net462\xunit.console.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.runner.utility\bin\Debug\net35\xunit.runner.utility.net35.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.console\bin\Debug\net46\xunit.console.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.console\bin\Debug\net472\xunit.console.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.console\bin\Debug\net471\xunit.console.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\test\test.xunit1\bin\Debug\net40\test.xunit1.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in E:\Projects\xunit\src\xunit.console\bin\Debug\net47\xunit.console.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    Test project test.xunit.runner.reporters does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    ========== Test discovery aborted: 0 Tests found in 2 sec ==========
    Test project test.xunit.runner.reporters does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.tdnet does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit.runner.utility does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    Test project test.xunit1 does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.


Following the recommendation to

    **It's recommended to reference NuGet test adapters in each test project in the solution.**

I add the visualstudio.xunit nuget package in version 2.4.1 to one of or all of Tests.Core.test.xunit.*, Tests.Runners.test.xunit.*, Test.v1.test.xunit1. But here it is already very unclear for me which version of the runner shall be used and which project should get the runner. 
I also wonder why I have to add that why the sln does not run out of the box.
Anyway, with each process that I am doing I end up at messages like these:

    [xUnit.net 00:00:00.15]   Discovering: test.xunit.execution (app domain = on [shadow copy], method display = ClassAndMethod, method display options = None)
    [xUnit.net 00:00:00.19] test.xunit.execution: Non-serializable data ('System.Object[]') found for 'ResolveGenericMethodTests.ResolveGenericType'; falling back to single test case.
    [xUnit.net 00:00:00.34]   Discovering: test.utility
    [xUnit.net 00:00:00.35]   Discovered:  test.utility
    [xUnit.net 00:00:00.24] test.xunit.execution: Non-serializable data ('System.Object[]') found for 'XunitTheoryTestCaseRunnerTests+ClassWithThrowingToString.Test'; falling back to single test case.
    [xUnit.net 00:00:00.24] test.xunit.execution: Non-serializable data ('System.Object[]') found for 'XunitTheoryTestCaseRunnerTests+ClassWithThrowingEnumerator.Test'; falling back to single test case.
    [xUnit.net 00:00:00.24] test.xunit.execution: Non-serializable data ('System.Object[]') found for 'TheoryDiscovererTests+NonSerializableEnumDataClass.TheTest'; falling back to single test case.
    [xUnit.net 00:00:00.51] test.xunit.execution: Non-serializable data ('System.Object[]') found for 'XmlTestExecutionVisitorTests+Xml.AddsErrorMessagesToXml'; falling back to single test case.
    [xUnit.net 00:00:00.52] test.xunit.execution: Non-serializable data ('Xunit2TheoryAcceptanceTests+TheoryTests+ClassWithOperatorConversions+Explicit[]') found for 'Xunit2TheoryAcceptanceTests+TheoryTests+ClassWithOperatorConversions.ArgumentDeclaredExplicitConversion'; falling back to single test case.
    [xUnit.net 00:00:00.52] test.xunit.execution: Non-serializable data ('Xunit2TheoryAcceptanceTests+TheoryTests+ClassWithOperatorConversions+Implicit[]') found for 'Xunit2TheoryAcceptanceTests+TheoryTests+ClassWithOperatorConversions.ArgumentDeclaredImplicitConversion'; falling back to single test case.
    [xUnit.net 00:00:00.52] test.xunit.execution: Non-serializable data ('System.Object[]') found for 'Xunit2TheoryAcceptanceTests+TheoryTests+GenericWithNonSerializableData.GenericTest'; falling back to single test case.

The amount of tests that is being found by the runner changes a lot depending on where I add the test adapter.

**In all cases I see no progress. It looks like not even a single test is being started.**


I have tried without success 
* visualstudio.xunit 2.4.1, 2.4.2, 2.4.3, 2.4.5,
* changing the language from my System Language de-DE to en-GB and en-US and rebooting
* Updating the system and Visual Studio

**Comment by bradwilson** [comment]
README has been updated to point to the new [`BUILDING.md`](https://github.com/xunit/visualstudio.xunit/blob/main/BUILDING.md) with instructions on how to build the project. Now that UWP has been removed, the requirements are very low, and the new command line build should just work without fuss.
