### ISSUE TITLE
xunit.runner.visualstudio/2.5.3 references 2.5.2 version of xunit

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/visualstudio.xunit#390]
xunit.runner.visualstudio.testadapter from `xunit.runner.visualstudio/2.5.3` references xunit/2.5.2 assemblies:

<img width="624" alt="image" src="https://github.com/xunit/visualstudio.xunit/assets/7412651/e6377fe8-f0bf-4b63-b924-8ca5a6834e60">

You can see that the assembly metadata points to `xunit.runner.utility.net452, Version=2.5.2.0`.

When using `xunit/2.5.3` in combination with `xunit.runner.visualstudio/2.5.3`, the assembly version of `xunit.runner.utility.net452` in the output directory is `2.5.3.0`. This leads to the following failure when invoking `dotnet test -f net462 --diag:log.txt` on a .NET Framework test app:

> TpTrace Warning: 0 : 14244, 3, 2023/10/30, 19:39:47.511, 3877462031738, testhost.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'xunit.runner.utility.net452, Version=2.5.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.
File name: 'xunit.runner.utility.net452, Version=2.5.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args) in /_/src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginCache.cs:line 513
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

The version is hardcoded to 2.5.2 here: https://github.com/xunit/visualstudio.xunit/blob/097b60584fb932d3dcff297de827c543c879c7f4/Versions.props#L13

cc @bradwilson

**Comment by bradwilson** [comment]
That's because 2.5.3 of the VS adapter was released with 2.5.2 of the core framework.

Why does it matter?

**Comment by bradwilson** [comment]
Are you coding against runner utility?

**Comment by bradwilson** [comment]
![image](https://github.com/xunit/visualstudio.xunit/assets/16944/3945262f-bedf-4f3f-a1b2-f0e14a36c241)

**Comment by ViktorHofer** [comment]
Yikes, I should have come up with a repro first... Let me get back to you.

**Comment by bradwilson** [comment]
Going to close this as it's not us. I've added comments to https://github.com/dotnet/runtime/issues/94183 and happy to help with any followup necessary there.
