### ISSUE TITLE
Catastrophic error deserializing item #34. System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by vgurramdt** [xunit/visualstudio.xunit#427]
I am receiving the following error when I try to run unit tests in azure devops using VSTest.

2024-12-05T18:55:09.6048339Z ##[debug]ProxyRunRequest: HandleLogMessage Entered
2024-12-05T18:55:09.6053905Z ##[error]RunMessage : [xUnit.net 00:00:01.71] Bc.Logic.AncillaryProduct.E2E: Catastrophic error deserializing item #34: System.ArgumentException: An item with the same key has already been added. Key: 7f27d8f5ea80f5832ab67b31a13fc75051225279
2024-12-05T18:55:09.6055246Z ##[debug]Processed: ##vso[task.logissue type=error;]RunMessage : [xUnit.net 00:00:01.71] Bc.Logic.AncillaryProduct.E2E: Catastrophic error deserializing item #34: System.ArgumentException: An item with the same key has already been added. Key: 7f27d8f5ea80f5832ab67b31a13fc75051225279
2024-12-05T18:55:09.6055911Z    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
2024-12-05T18:55:09.6057642Z    at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)

**Comment by bradwilson** [comment]
Can you provide a repro project?

**Comment by bradwilson** [comment]
Hello,

As part of the effort to clean up older issues, this is being closed due to age. If this is still applicable with v3, please open a new issue (with an attached v3 repro) so it can be re-evaluated and categorized.

Thanks!
