### ISSUE TITLE
ArgumentException ("An item with the same key has already been added.") With [Theory()] and [InlineData(...)]

### ISSUE THREAD

**Issue by MichaelFStarke** [xunit/visualstudio.xunit#45]
I get various errors in the Tests output:

running a single theory/inline datum:
```C#
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain. This can happen if the test(s) started a thread but did not stop it. Make sure that all the threads started by the test(s) are stopped before completion.
```

running 2+ theories/inline data:
```C#
An exception occurred while invoking executor 'executor://xunit/VsTestRunner2': An item with the same key has already been added.
```

sometimes I get a full stack trace:
```C#
------ Run test started ------
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IFrameworkHandle frameworkHandle, List`1 toDispose, AssemblyRunInfo runInfo, Stopwatch stopwatch)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.<>c__DisplayClass3c.<RunTestsInAssemblyAsync>b__3a()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.<>c__DisplayClass3c.<RunTestsInAssemblyAsync>b__3b(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IFrameworkHandle frameworkHandle, List`1 toDispose, AssemblyRunInfo runInfo, Stopwatch stopwatch)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.<>c__DisplayClass3c.<RunTestsInAssemblyAsync>b__3a()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.<>c__DisplayClass3c.<RunTestsInAssemblyAsync>b__3b(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
========== Run test finished: 0 run (0:00:02.4045018) ==========
```

packages:
```XML
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="xunit" version="2.0.0-rc2-build2857" targetFramework="net45" />
  <package id="xunit.abstractions" version="2.0.0-rc2-build2857" targetFramework="net45" />
  <package id="xunit.assert" version="2.0.0-rc2-build2857" targetFramework="net45" />
  <package id="xunit.core" version="2.0.0-rc2-build2857" targetFramework="net45" />
  <package id="xunit.extensibility.core" version="2.0.0-rc2-build2857" targetFramework="net45" />
  <package id="xunit.runner.visualstudio" version="2.0.0-rc2-build1043" targetFramework="net45" />
</packages>
```

**Comment by MichaelFStarke** [comment]
In a minimal test solution (same packages as above) with a single Theory(), with three InlineData(), "Run All" never succeeds (with the second error message from above). Running two out of three (select two => run selected) sometimes succeeds sometimes fails (with the second error message from above).  Running a single datum always succeeds, with no errors.

**Comment by bradwilson** [comment]
Likely related to https://github.com/xunit/xunit/issues/303

**Comment by bradwilson** [comment]
The problem is going to be related to a last minute fix we put into RC2 to do lookups based on unique IDs instead of test case instances: https://github.com/xunit/visualstudio.xunit/commit/d1d0986a221583584747a8a492984b24cdba21e5

**Comment by MichaelFStarke** [comment]
Am I reading xunit/src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs correctly that the UniqueID is the SHA1 hash of the assembly name, class name, method name, and method args all mashed together?  Isn't that **always** going to clash for theories with more than a single datum?

Is it truly a requirement of the UniqueID that it be stable across multiple runs on the same compiled binary?  (Reading from ITestCase.UniqueID)  Are test runs not independent (even if they are visited against the same compiled binary)?

**Comment by MichaelFStarke** [comment]
Reading the array serializer, it looks like it serializes the arg values, so it's looking increasingly like this is related to #303.

**Comment by bradwilson** [comment]
I agree that one of the major faults is treating null and empty string the same.

The other is that I think I have to move back to defaulting to using instance identity as the lookup key, and only fall back to unique ID when the instance lookup doesn't suffice (because of the oddity of how `STATestCase` encapsulates rather than derives from `XunitTestCase`, which breaks the identity expectations for test message reporting). I still want to accommodate this (degenerate) use case, since it makes things much easier to implement.

The requirement for stability is that it has to survive platform shifts across multiple processes, because that's exactly how the Visual Studio runner works. Discovery happens in one process, and execution happens in another process (potentially on an entirely different device and/or OS, given that Windows Phone tests run inside an emulator VM). In addition, we need the unique ID to be stable across here because the unique ID is sometimes used as the unique identifier to VS (when multiple tests point to the same test method, as in the case of theories).

For serialization purposes, the only thing we have that can cross that boundary is a string, which mandates being able to serialize test cases to a pure string. This is always going to be possible for facts, given that reconstructing a fact simply involves knowing the type and method. For theories, we can serialize it so long as all data rows are serializable; if they aren't, they we are forced to fall back to using a single test case for the whole theory, and the user is unable to run individual theory data rows.

**Comment by MichaelFStarke** [comment]
Interesting.  So a synthetic identifier like a Guid wouldn't suffice since the actual object isn't shared among the different phases/processes.  The identifier has to be a "natural" identifier derived from the object itself.  That makes a lot of sense.  Thanks for taking the time to describe that.

**Comment by AlexanderSher** [comment]
Brad, can you give a hint on how to debug issues with discovery? Attaching debugger to VS doesn't work, Debugger.Break doesn't work either.

**Comment by bradwilson** [comment]
Visual Studio launches separate processes; the process names are something like vstest.discoveryengine.exe and vstest.executionengine.exe, if memory serves. The first time it does discovery (or execution) is when it launches those processes.

The simplest way to debug issues with discovery is to let it do discovery once (so the process is started), and then attached to the discoveryengine process.

**Comment by jiffypopjr** [comment]
Ran into the same problem, it didn't like the following -- I had to comment either the "" or the " " one (the null with the others was fine).

[InlineData(null)]
[InlineData("")]
[InlineData(" ")]

**Comment by MichaelFStarke** [comment]
Aye.  That's the most common three InlineData() items that I use, and what lead me to start tracking this down.

**Comment by jorgeyanesdiez** [comment]
I have the same problem: here's a minimal project to reproduce.
https://github.com/jorgeyanesdiez/visualstudio.xunit.bugreport.20150220/
Sorry if this is not the way to link an issue, I'm a github n00b.

**Comment by AlexanderSher** [comment]
Great!

Are you going to update the nuget package during the weekend?

**Comment by bradwilson** [comment]
Monday, probably.
