### ISSUE TITLE
VS runner exception with 2.0.0-rc3

### ISSUE THREAD

**Issue by rmaclean** [xunit/visualstudio.xunit#48]
Upgraded to 2.0.0-rc3 and when I try to run the tests which did work previously (tested with 2.0.0-rc1) we get the following error:

    [xUnit.net 00:00:00.1600196] Exception discovering tests from BirdLasser.Tests.dll:  System.MissingMethodException: Constructor on type 'Xunit.Sdk.TestFrameworkProxy' not found.
    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
    at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
    at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
    at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
    at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder)
    at Xunit.XunitFrontController.CreateInnerController()
    at Xunit.XunitFrontController.get_InnerController()
    at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, IMessageLogger logger, Func`3 visitorFactory, Action`3 visitComplete, Stopwatch stopwatch)

**Comment by bradwilson** [comment]
You have a version mismatch: everything (xunit & VS runner) should be RC 3.

Also, make sure you have cleaned your packages folder, as its possible that you have a leftover version of the old runner still in there (which Visual Studio is picking up).

**Comment by rmaclean** [comment]
Definitely made sure both the runner & test was upgraded. Could very well be the packages thing. Any checklist for upgrading, so that I can also make sure the rest of the team does the right steps?

**Comment by bradwilson** [comment]
Whenever packages are upgraded, I always do a `git clean -xdf` (after staging the commit) to ensure that I can verify the NuGet package restore, and I know exactly what's being downloaded.

**Comment by hoppersoft** [comment]
This appears to be an issue if you upgrade to RC3 and try to discover tests without first restarting VS; it looks like VS is keeping the old version in memory. I had this exact issue and a restart of VS appears to have resolved it.

**Comment by bradwilson** [comment]
As an alternative, you can find the hosting processes that it uses for discovery and execution and just kill them (in task manager). I don't remember their names of the top of my head but they're fairly obvious (like `vs.discoveryengine.exe` and `vs.executionengine.exe` or something similar)
