### ISSUE TITLE
Test Discovery throws BadImageFormatException

### ISSUE THREAD

**Issue by rickardgranberg** [xunit/visualstudio.xunit#62]
We have a solution with mixed C# and C++ projects. Unit testing of C++ is done with mstest, but it appears that the xunit test runner/discoverer is not prepared to find a C++ dll, as the attempt to load it as an assembly throws a BadImageFormatException:

[xUnit.net 00:00:00.2870680] Exception discovering tests from Library.UnitTest.Cpp: System.BadImageFormatException: Could not load file or assembly 'Library.UnitTest.Cpp.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'Library.UnitTest.Cpp.dll' ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
   at Xunit.RemoteAppDomainManager.CreateObjectTObject
   at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink)
   at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink)
   at Xunit.Xunit2..ctor(ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.XunitFrontController.get_TargetFramework()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTestsTVisitor

**Comment by bradwilson** [comment]
This is expected behavior. We log all exceptions that happen during discovery. Since you are not expecting xUnit.net to run this assembly, you can safely ignore this exception.

**Comment by rickardgranberg** [comment]
I have no problem ignoring this exception. The TFS build (which also runs the tests) does however, as this exception leads to a "Partially Succeeded" build. I'm currently investigating using the <TreatTestAdapterErrorsAsWarnings> option in our .runsettings file, but I'm not sure if I want to enable this as it may suppress other errors. Is there a way to suppress specific exceptions?

**Comment by bradwilson** [comment]
We could log it with a different level than Error. I presume that's what the issue is.

https://github.com/xunit/visualstudio.xunit/blob/83ea70d90b340498e12d177b5e36ff8819bae23e/xunit.runner.visualstudio.testadapter/VsTestRunner.cs#L159-L163

**Comment by bradwilson** [comment]
And also:

https://github.com/xunit/visualstudio.xunit/blob/83ea70d90b340498e12d177b5e36ff8819bae23e/xunit.runner.visualstudio.testadapter/VsTestRunner.cs#L152-L154

**Comment by rickardgranberg** [comment]
Yes, that would make TFS (and me) happy :)
