### ISSUE TITLE
Unexpected exceptions during test execution of v1 theories in VS 2015 (RC)

### ISSUE THREAD

**Issue by bradwilson** [xunit/visualstudio.xunit#72]
While working through issues related to #71, it was discovered that VS2015 is throwing exceptions during reporting of theories with v1 tests, where VS2013 previously was not.

The output for VS2013 is as follows:

```
[xUnit.net 00:00:00.6636602] v1_net45: Performing RecordStart for test case BasicTests.Theory
[xUnit.net 00:00:00.6656988] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.6711453] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.6735760] v1_net45: Performing RecordResult (Fail) for test case BasicTests.Theory
[xUnit.net 00:00:00.6744458] v1_net45: Performing RecordEnd for test case BasicTests.Theory
```

The output for VS2015 is as follows:

```
[xUnit.net 00:00:00.9678382] v1_net45: Performing RecordStart for test case BasicTests.Theory
[xUnit.net 00:00:00.9691659] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.9704055] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.9722230] v1_net45: Error occured while RecordResult (Pass) for test case BasicTests.Theory: System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordResult(TestResult testResult)
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.<>c__DisplayClass10_0.<Visit>b__0()
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.TryAndReport(String actionDescription, ITestCase testCase, Action action)
[xUnit.net 00:00:00.9737970] v1_net45: Performing RecordResult (Fail) for test case BasicTests.Theory
[xUnit.net 00:00:00.9747519] v1_net45: Error occured while RecordResult (Fail) for test case BasicTests.Theory: System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordResult(TestResult testResult)
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.<>c__DisplayClass9_0.<Visit>b__0()
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.TryAndReport(String actionDescription, ITestCase testCase, Action action)
[xUnit.net 00:00:00.9751302] v1_net45: Performing RecordEnd for test case BasicTests.Theory
```

In both cases, all the results are actually showing in Visual Studio, so the issue is seemingly benign for the moment.

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#492
